/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest video metadata and run AI trend analysis
         * @description Accepts YouTube video metadata (e.g. from n8n), samples to the top 50 by view count, runs the configured LLM chain, and upserts an idempotent daily trend report. Send `X-API-Key` matching the server `API_KEY` environment variable.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestRequest"];
                };
            };
            responses: {
                /** @description Trend report created or replaced for the UTC analysis day */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestCreatedResponse"];
                    };
                };
                /** @description Invalid JSON body or validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Missing or invalid X-API-Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description LLM, parse, or persistence failure */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List daily trend reports
         * @description Returns recent trend reports (newest first), each with 3–5 trends and the YouTube videos linked to each trend.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of daily reports */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyTrendReport"][];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendsErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IngestCreatedResponse: {
            /** @enum {string} */
            message: "Ingested";
            /** Format: uuid */
            reportId: string;
        };
        ErrorBody: {
            error: string;
        };
        IngestRequest: {
            videos: components["schemas"]["VideoMetadata"][];
        };
        VideoMetadata: {
            videoId: string;
            channelId: string;
            channelTitle?: string;
            title: string;
            description: string;
            /** Format: date-time */
            publishedAt: string;
            viewCount: number;
        };
        DailyTrendReport: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            analysisDate: string;
            trends: components["schemas"]["TrendReportTrend"][];
            totalVideosAnalyzed: number;
        };
        TrendReportTrend: {
            topicName: string;
            explanation: string;
            videos: components["schemas"]["TrendVideoSnippet"][];
        };
        TrendVideoSnippet: {
            videoId: string;
            title: string;
        };
        TrendsErrorBody: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
